import { useMemo } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import {
  AlertCircle,
  ArrowLeft,
  ClipboardList,
  Sparkles,
  Trophy,
  CheckCircle,
  Activity,
  Bookmark
} from 'lucide-react'
import { Badge } from '../components/ui/Badge'
import { Button } from '../components/ui/Button'
import { Card } from '../components/ui/Card'
import { EmptyState } from '../components/ui/EmptyState'
import type { InterviewArchive } from '../types'

function readInterviewArchive(sessionId?: string): InterviewArchive | null {
  // Try loading from list
  const saved = localStorage.getItem('userSessions')
  if (saved) {
    try {
      const list = JSON.parse(saved) as InterviewArchive[]
      const found = list.find(s => s.sessionId === sessionId)
      if (found) return found
    } catch (e) {
      console.error(e)
    }
  }

  // Fallback to lastSession
  const raw = localStorage.getItem('lastSession')
  if (!raw) {
    return null
  }

  try {
    const parsed = JSON.parse(raw) as InterviewArchive
    if (!parsed || typeof parsed !== 'object') {
      return null
    }

    if (sessionId && parsed.sessionId !== sessionId) {
      return null
    }

    return parsed
  } catch {
    return null
  }
}

export function FeedbackReport() {
  const { id } = useParams()
  const navigate = useNavigate()

  const archive = useMemo(() => readInterviewArchive(id), [id])

  if (!archive) {
    return (
      <EmptyState
        icon={ClipboardList}
        title="No feedback report yet"
        message="Complete a conversation session first so the archive can be attached here."
        actionLabel="Start Interview"
        onAction={() => navigate('/interview')}
      />
    )
  }

  const evaluation = archive.evaluation

  return (
    <div className="space-y-6 max-w-5xl mx-auto px-4 py-4">
      {/* Header card */}
      <div className="flex flex-col gap-4 rounded-2xl bg-white p-6 shadow-sm border border-gray-100 dark:bg-gray-900 dark:border-gray-800 lg:flex-row lg:items-center lg:justify-between">
        <div>
          <div className="mb-3 flex flex-wrap gap-2">
            <Badge label={archive.metadata.jobRole} variant="info" />
            <Badge label={`${archive.metadata.durationMinutes} min`} variant="warning" />
            <Badge label={archive.metadata.answerMode.toUpperCase()} variant="default" />
          </div>
          <h1 className="text-3xl font-extrabold text-gray-900 dark:text-gray-100 tracking-tight">
            Detailed Feedback Report
          </h1>
          <p className="mt-1.5 text-sm text-gray-500 dark:text-gray-400">
            Performance summary and dimension metric scorecard generated by Emma.
          </p>
        </div>

        <Button type="button" variant="secondary" onClick={() => navigate('/dashboard')}>
          <ArrowLeft className="h-4 w-4" />
          Back to Dashboard
        </Button>
      </div>

      {evaluation ? (
        <div className="grid gap-6 md:grid-cols-3">
          
          {/* Main summary card - 2 cols span */}
          <div className="md:col-span-2 space-y-6">
            
            {/* Summary details */}
            <Card className="p-6 border border-gray-100 shadow-sm dark:border-gray-800">
              <div className="flex items-center gap-2 mb-4">
                <Sparkles className="h-5 w-5 text-primary animate-pulse" />
                <h2 className="text-lg font-bold text-gray-900 dark:text-gray-100">
                  Performance Summary
                </h2>
              </div>
              <p className="text-sm text-gray-650 dark:text-gray-350 leading-relaxed">
                {evaluation.summary}
              </p>
            </Card>

            {/* Strengths & Weaknesses */}
            <Card className="p-6 border border-gray-100 shadow-sm dark:border-gray-800 space-y-5">
              <div>
                <h3 className="font-bold text-sm text-emerald-700 dark:text-emerald-400 uppercase tracking-wider mb-2.5 flex items-center gap-1.5">
                  <CheckCircle className="h-4 w-4 shrink-0" />
                  Key Strengths
                </h3>
                <ul className="space-y-2 text-xs pl-2 text-gray-650 dark:text-gray-350">
                  {evaluation.strengths.map((s, idx) => (
                    <li key={idx} className="flex gap-2 items-start">
                      <span className="h-1.5 w-1.5 bg-emerald-500 rounded-full mt-1.5 shrink-0" />
                      <span>{s}</span>
                    </li>
                  ))}
                </ul>
              </div>

              <div className="pt-4 border-t border-gray-100 dark:border-gray-800">
                <h3 className="font-bold text-sm text-amber-700 dark:text-amber-400 uppercase tracking-wider mb-2.5 flex items-center gap-1.5">
                  <AlertCircle className="h-4 w-4 shrink-0" />
                  Growth Opportunities
                </h3>
                <ul className="space-y-2 text-xs pl-2 text-gray-650 dark:text-gray-350">
                  {evaluation.opportunities.map((w, idx) => (
                    <li key={idx} className="flex gap-2 items-start">
                      <span className="h-1.5 w-1.5 bg-amber-500 rounded-full mt-1.5 shrink-0" />
                      <span>{w}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </Card>

            {/* Turn Count list */}
            <Card className="p-6 border border-gray-100 shadow-sm dark:border-gray-800 space-y-4">
              <h3 className="font-bold text-sm text-gray-800 dark:text-gray-200">
                Turn Analytics Checklist
              </h3>
              
              <div className="grid gap-3 sm:grid-cols-2 text-xs text-gray-500">
                <div className="bg-gray-50 dark:bg-gray-950 p-3 rounded-xl border border-gray-100 dark:border-gray-900">
                  <span className="block font-bold text-gray-700 dark:text-gray-300">Candidate Speeches</span>
                  <span className="text-lg font-extrabold text-primary mt-1 block">
                    {archive.candidateResponses.length} turns captured
                  </span>
                </div>
                <div className="bg-gray-50 dark:bg-gray-950 p-3 rounded-xl border border-gray-100 dark:border-gray-900">
                  <span className="block font-bold text-gray-700 dark:text-gray-300">AI Prompts Spoken</span>
                  <span className="text-lg font-extrabold text-success mt-1 block">
                    {archive.aiResponses.length} questions asked
                  </span>
                </div>
              </div>
            </Card>

          </div>

          {/* Right side: overall score and dimensions */}
          <div className="space-y-6">
            
            {/* Overall Score */}
            <Card className="p-6 text-center border border-gray-100 shadow-sm dark:border-gray-800 flex flex-col items-center">
              <Trophy className="h-9 w-9 text-amber-500 mb-2" />
              <span className="text-xs font-bold text-gray-400 uppercase tracking-wide">Overall score</span>
              <span className="text-5xl font-extrabold text-primary tracking-tight my-2">
                {evaluation.overallScore ?? 7.5}
              </span>
              <span className="text-[10px] text-gray-400 uppercase font-semibold">Scale 1-10</span>
            </Card>

            {/* Dimensions */}
            {evaluation.dimensions && (
              <Card className="p-6 border border-gray-100 shadow-sm dark:border-gray-800">
                <h3 className="font-bold text-xs uppercase tracking-wider text-gray-400 mb-4 flex items-center gap-1.5">
                  <Activity className="h-4 w-4 text-primary" />
                  Dimension Breakdown
                </h3>

                <div className="space-y-3.5">
                  {evaluation.dimensions.map((dim) => (
                    <div key={dim.dimension} className="space-y-1">
                      <div className="flex justify-between text-xs font-semibold text-gray-600 dark:text-gray-400">
                        <span>{dim.dimension}</span>
                        <span>{dim.score}/10</span>
                      </div>
                      <div className="h-1.5 w-full bg-gray-100 dark:bg-gray-800 rounded-full overflow-hidden">
                        <div
                          className="h-full bg-primary rounded-full"
                          style={{ width: `${dim.score * 10}%` }}
                        />
                      </div>
                    </div>
                  ))}
                </div>
              </Card>
            )}

            {/* Recommendation focus */}
            <Card className="p-6 border border-gray-100 shadow-sm dark:border-gray-800">
              <h3 className="font-bold text-xs uppercase tracking-wider text-gray-400 mb-3.5 flex items-center gap-1.5">
                <Bookmark className="h-4 w-4 text-accent" />
                Focus Themes
              </h3>
              
              <ul className="space-y-2 text-xs text-gray-600 dark:text-gray-400">
                {evaluation.followUpThemes.map((theme, i) => (
                  <li key={i} className="flex gap-2">
                    <span className="mt-1 h-1.5 w-1.5 bg-accent rounded-full shrink-0" />
                    <span>{theme}</span>
                  </li>
                ))}
              </ul>
            </Card>
          </div>

        </div>
      ) : (
        <Card className="border border-dashed border-gray-300 bg-gray-50/50 p-6 dark:border-gray-750 dark:bg-gray-900/40">
          <div className="flex items-start gap-3">
            <AlertCircle className="mt-0.5 h-5 w-5 text-warning" />
            <div>
              <p className="font-semibold text-gray-900 dark:text-gray-100">
                Evaluation Pending
              </p>
              <p className="mt-1 text-sm text-gray-600 dark:text-gray-300">
                This interview transcript does not contain any compiled scores or ratings yet. Run a full practice session to generate results.
              </p>
            </div>
          </div>
        </Card>
      )}
    </div>
  )
}
