import type {
  Evaluation,
  InterviewSession,
  Notification,
  PracticeTask,
  Question,
  Response,
  User,
} from '../types'

export const mockUser: User = {
  id: 'user-001',
  fullName: 'Aarav Sharma',
  email: 'aarav.sharma@example.com',
  role: 'candidate',
  avatarUrl: 'https://i.pravatar.cc/150?img=12',
  createdAt: '2026-05-18T09:30:00.000Z',
}

export const mockQuestions: Question[] = [
  {
    id: 'q-001',
    text: 'Explain the difference between `useMemo` and `useCallback` in React.',
    category: 'Technical',
    difficulty: 'Easy',
    tags: ['react', 'performance'],
    createdBy: 'coach-01',
    createdAt: '2026-05-20T10:00:00.000Z',
  },
  {
    id: 'q-002',
    text: 'How would you prevent unnecessary re-renders in a large dashboard?',
    category: 'Technical',
    difficulty: 'Medium',
    tags: ['react', 'optimization'],
    createdBy: 'coach-02',
    createdAt: '2026-05-20T10:20:00.000Z',
  },
  {
    id: 'q-003',
    text: 'Tell me about a time you had to lead a team through ambiguity.',
    category: 'Behavioral',
    difficulty: 'Medium',
    tags: ['leadership', 'teamwork'],
    createdBy: 'coach-01',
    createdAt: '2026-05-21T08:15:00.000Z',
  },
  {
    id: 'q-004',
    text: 'Why are you interested in this role and what excites you about it?',
    category: 'HR',
    difficulty: 'Easy',
    tags: ['motivation', 'culture'],
    createdBy: 'coach-03',
    createdAt: '2026-05-21T11:45:00.000Z',
  },
  {
    id: 'q-005',
    text: 'Design a rate-limited API endpoint for a high-traffic product.',
    category: 'Technical',
    difficulty: 'Hard',
    tags: ['system-design', 'backend'],
    createdBy: 'coach-02',
    createdAt: '2026-05-22T13:10:00.000Z',
  },
  {
    id: 'q-006',
    text: 'Describe a conflict with a teammate and how you resolved it.',
    category: 'Behavioral',
    difficulty: 'Easy',
    tags: ['conflict-resolution', 'communication'],
    createdBy: 'coach-04',
    createdAt: '2026-05-22T15:00:00.000Z',
  },
  {
    id: 'q-007',
    text: 'How do you prioritize tasks when every stakeholder says their request is urgent?',
    category: 'HR',
    difficulty: 'Medium',
    tags: ['prioritization', 'stakeholder-management'],
    createdBy: 'coach-03',
    createdAt: '2026-05-23T09:40:00.000Z',
  },
  {
    id: 'q-008',
    text: 'What happens when a browser receives a `Promise.reject()` from an async handler?',
    category: 'Technical',
    difficulty: 'Medium',
    tags: ['javascript', 'async'],
    createdBy: 'coach-05',
    createdAt: '2026-05-24T07:25:00.000Z',
  },
  {
    id: 'q-009',
    text: 'Share an example of taking feedback and improving your work quickly.',
    category: 'Behavioral',
    difficulty: 'Easy',
    tags: ['growth', 'feedback'],
    createdBy: 'coach-01',
    createdAt: '2026-05-24T12:30:00.000Z',
  },
  {
    id: 'q-010',
    text: 'Where do you see your career progressing over the next three years?',
    category: 'HR',
    difficulty: 'Hard',
    tags: ['career', 'goals'],
    createdBy: 'coach-04',
    createdAt: '2026-05-25T17:05:00.000Z',
  },
]

export const mockSessions: InterviewSession[] = [
  {
    id: 'session-001',
    candidateId: mockUser.id,
    jobRole: 'Frontend Developer',
    difficulty: 'Medium',
    totalQuestions: 5,
    answerMode: 'text',
    status: 'completed',
    overallScore: 8,
    createdAt: '2026-06-01T09:00:00.000Z',
    completedAt: '2026-06-01T09:48:00.000Z',
  },
  {
    id: 'session-002',
    candidateId: mockUser.id,
    jobRole: 'Full Stack Developer',
    difficulty: 'Hard',
    totalQuestions: 7,
    answerMode: 'voice',
    status: 'active',
    createdAt: '2026-06-08T14:20:00.000Z',
  },
  {
    id: 'session-003',
    candidateId: mockUser.id,
    jobRole: 'Data Scientist',
    difficulty: 'Easy',
    totalQuestions: 3,
    answerMode: 'text',
    status: 'abandoned',
    overallScore: 6,
    createdAt: '2026-05-28T11:10:00.000Z',
  },
]

export const mockNotifications: Notification[] = [
  {
    id: 'notif-001',
    title: 'Session completed',
    description: 'Your frontend interview session has been scored and is ready to review.',
    status: 'unread',
    category: 'session',
    createdAt: '2026-06-01T09:50:00.000Z',
  },
  {
    id: 'notif-002',
    title: 'New feedback report',
    description: 'Coach comments were added to your latest mock interview.',
    status: 'read',
    category: 'feedback',
    createdAt: '2026-06-01T10:05:00.000Z',
  },
  {
    id: 'notif-003',
    title: 'Practice task updated',
    description: 'Your weekly speaking practice task has been marked completed.',
    status: 'read',
    category: 'system',
    createdAt: '2026-06-02T08:15:00.000Z',
  },
  {
    id: 'notif-004',
    title: 'Upcoming session reminder',
    description: 'Your next interview practice starts in 30 minutes.',
    status: 'unread',
    category: 'session',
    createdAt: '2026-06-08T13:50:00.000Z',
  },
  {
    id: 'notif-005',
    title: 'Confidence improved',
    description: 'Your confidence score increased by 12% compared to last week.',
    status: 'unread',
    category: 'feedback',
    createdAt: '2026-06-09T07:30:00.000Z',
  },
  {
    id: 'notif-006',
    title: 'Profile reminder',
    description: 'Complete your profile to unlock tailored role suggestions.',
    status: 'read',
    category: 'system',
    createdAt: '2026-06-10T16:45:00.000Z',
  },
]

export const mockPracticeTasks: PracticeTask[] = [
  { id: 'task-001', day: 'Mon', topic: 'Behavioral storytelling', questionCount: 3, status: 'completed' },
  { id: 'task-002', day: 'Tue', topic: 'React component patterns', questionCount: 5, status: 'completed' },
  { id: 'task-003', day: 'Wed', topic: 'Data structures revision', questionCount: 7, status: 'pending' },
  { id: 'task-004', day: 'Thu', topic: 'System design fundamentals', questionCount: 5, status: 'pending' },
  { id: 'task-005', day: 'Fri', topic: 'Leadership and teamwork', questionCount: 3, status: 'completed' },
  { id: 'task-006', day: 'Sat', topic: 'HR round preparation', questionCount: 3, status: 'pending' },
  { id: 'task-007', day: 'Sun', topic: 'Full mock interview', questionCount: 10, status: 'pending' },
]

const mockResponses: Response[] = [
  {
    id: 'resp-001',
    sessionId: 'session-001',
    questionId: 'q-001',
    answerText: 'I use useMemo to memoize calculated values and useCallback to memoize function references.',
    score: 9,
    feedback: 'Clear and accurate explanation with a strong practical framing.',
    goodPoints: ['Correct distinction', 'Concise explanation', 'Good example usage'],
    improvements: ['Mention dependency arrays', 'Add a real-world scenario'],
  },
  {
    id: 'resp-002',
    sessionId: 'session-001',
    questionId: 'q-003',
    answerText: 'I aligned the team on goals, split the work into small checkpoints, and kept everyone updated daily.',
    score: 8,
    feedback: 'Structured response with strong ownership and communication.',
    goodPoints: ['Clear leadership', 'Good collaboration', 'Action-oriented'],
    improvements: ['Add measurable impact', 'Explain how you handled pushback'],
  },
  {
    id: 'resp-003',
    sessionId: 'session-001',
    questionId: 'q-004',
    answerText: 'I value the chance to build user-facing products and improve my fundamentals in a fast-paced team.',
    score: 7,
    feedback: 'Solid motivation, though it could be more tailored to the company.',
    goodPoints: ['Positive tone', 'Career alignment', 'Simple structure'],
    improvements: ['Reference the company mission', 'Be more specific about growth goals'],
  },
]

export const mockEvaluation: Evaluation = {
  id: 'eval-001',
  sessionId: 'session-001',
  overallScore: 8,
  dimensions: [
    { dimension: 'Technical Knowledge', score: 9 },
    { dimension: 'Communication', score: 8 },
    { dimension: 'Confidence', score: 7 },
    { dimension: 'Problem Solving', score: 8 },
    { dimension: 'Clarity', score: 9 },
  ],
  weakAreas: ['Handling follow-up questions', 'Adding deeper examples', 'Quantifying impact'],
  responses: mockResponses,
}
